apiVersion: v1
kind: Pod
metadata:
  name: cheftest
spec:
  volumes:
  - name: cookbook
    hostPath:
      # enter the local cookbook path to mount
      path: /host_mnt/c/GitRepos/chefconf19/cookbooks/chefconf
      type: Directory
  containers:
  - name: cheflocal
    image: cheflocal:latest
    resources:
      requests:
        memory: "256Mi"
        cpu: "500m"
      limits:
        memory: "256Mi"
        cpu: "500m"
    command:
    - sleep
    args:
    - infinity
    volumeMounts:
    - mountPath: /tmp/cookbook
      name: cookbook
    env:
      - name: COOKBOOK_PATH
        value: /tmp/cookbook
    imagePullPolicy: Never
    